//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RGR_II.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RGR_II.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \tConnection.
        /// </summary>
        internal static string ConnectionPrefix {
            get {
                return ResourceManager.GetString("ConnectionPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[AktivniiOtdih] (
        ///    [ID]        INT      DEFAULT ((0)) NOT NULL,
        ///	[FF]  TINYINT       DEFAULT ((0)) NULL,
        ///    [FS]  TINYINT       DEFAULT ((0)) NULL,
        ///    [FT]  TINYINT       DEFAULT ((0)) NULL,
        ///	PRIMARY KEY (ID)
        ///);.
        /// </summary>
        internal static string Create_AktivniiOtdih {
            get {
                return ResourceManager.GetString("Create_AktivniiOtdih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Arhitectura] (
        ///    [ID]        INT      DEFAULT ((0)) NOT NULL,
        ///	[FF]  TINYINT       DEFAULT ((0)) NULL,
        ///    [FS]  TINYINT       DEFAULT ((0)) NULL,
        ///	PRIMARY KEY (ID)
        ///);.
        /// </summary>
        internal static string Create_Arhitectura {
            get {
                return ResourceManager.GetString("Create_Arhitectura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[BolshieGoroda] (
        ///    [ID]        INT      DEFAULT ((0)) NOT NULL,
        ///	[FF]  TINYINT       DEFAULT ((0)) NULL,
        ///    [FS]  TINYINT       DEFAULT ((0)) NULL,
        ///    [FT]  TINYINT       DEFAULT ((0)) NULL,
        ///	PRIMARY KEY (ID)
        ///);.
        /// </summary>
        internal static string Create_BolshieGoroda {
            get {
                return ResourceManager.GetString("Create_BolshieGoroda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Gori] (
        ///    [ID]        INT      DEFAULT ((0)) NOT NULL,
        ///	[FF]   TINYINT       DEFAULT ((0)) NULL,
        ///    [FS]   TINYINT       DEFAULT ((0)) NULL,
        ///    [FT]   TINYINT       DEFAULT ((0)) NULL,
        ///	PRIMARY KEY (ID)
        ///);.
        /// </summary>
        internal static string Create_Gori {
            get {
                return ResourceManager.GetString("Create_Gori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[MalenkieGoroda] (
        ///    [ID]        INT      DEFAULT ((0)) NOT NULL,
        ///	[FF]  TINYINT       DEFAULT ((0)) NULL,
        ///    [FS]  TINYINT       DEFAULT ((0)) NULL,
        ///	PRIMARY KEY (ID)
        ///);.
        /// </summary>
        internal static string Create_MalenkieGoroda {
            get {
                return ResourceManager.GetString("Create_MalenkieGoroda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[OtdihVKompanii] (
        ///    [ID]        INT      DEFAULT ((0)) NOT NULL,
        ///	[FF] TINYINT       DEFAULT ((0)) NULL,
        ///    [FS] TINYINT       DEFAULT ((0)) NULL,
        ///	PRIMARY KEY (ID)
        ///);.
        /// </summary>
        internal static string Create_OtdihVKompanii {
            get {
                return ResourceManager.GetString("Create_OtdihVKompanii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Reki] (
        ///    [ID]        INT      DEFAULT ((0)) NOT NULL,
        ///	[FF]   TINYINT       DEFAULT ((0)) NULL,
        ///    [FS]   TINYINT       DEFAULT ((0)) NULL,
        ///    [FT]   TINYINT       DEFAULT ((0)) NULL,
        ///	PRIMARY KEY (ID)
        ///);.
        /// </summary>
        internal static string Create_Reki {
            get {
                return ResourceManager.GetString("Create_Reki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Rules] (
        ///    [ID]        INT      IDENTITY(1,1),
        ///    [ID_FK]		INT      DEFAULT 0 NOT NULL,
        ///    [P3]       TINYINT       DEFAULT 0 NOT NULL,
        ///    [O_nP4]    TINYINT       DEFAULT 0 NOT NULL,
        ///    [D8]       TINYINT       DEFAULT 0 NOT NULL,
        ///    [T_S15]    TINYINT       DEFAULT 0 NOT NULL,
        ///    [Name]      VARCHAR (150) NULL
        ///	PRIMARY KEY (ID),
        ///	FOREIGN KEY (ID_FK) REFERENCES AktivniiOtdih (ID),
        ///	FOREIGN KEY (ID_FK) REFERENCES OtdihVKompanii (ID),
        ///	FOREIGN KEY (ID_FK) REFERENCES Arh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_Rules {
            get {
                return ResourceManager.GetString("Create_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[SostoanieZdorovia] (
        ///    [ID]        INT      DEFAULT ((0)) NOT NULL,
        ///	[FF] TINYINT       DEFAULT ((0)) NULL,
        ///    [FS] TINYINT       DEFAULT ((0)) NULL,
        ///    [FT] TINYINT       DEFAULT ((0)) NULL,
        ///	PRIMARY KEY (ID)
        ///);.
        /// </summary>
        internal static string Create_SostoanieZdorovia {
            get {
                return ResourceManager.GetString("Create_SostoanieZdorovia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Temp_Hight] (
        ///    [ID]        INT      DEFAULT ((0)) NOT NULL,
        ///	[FF] TINYINT       DEFAULT ((0)) NULL,
        ///    [FS] TINYINT       DEFAULT ((0)) NULL,
        ///	PRIMARY KEY (ID)
        ///);.
        /// </summary>
        internal static string Create_Temp_Hight {
            get {
                return ResourceManager.GetString("Create_Temp_Hight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Temp_Low] (
        ///    [ID]        INT      DEFAULT ((0)) NOT NULL,
        ///	[FF] TINYINT       DEFAULT ((0)) NULL,
        ///    [FS] TINYINT       DEFAULT ((0)) NULL,
        ///	PRIMARY KEY (ID)
        ///);.
        /// </summary>
        internal static string Create_Temp_Low {
            get {
                return ResourceManager.GetString("Create_Temp_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[VoennaaTematika] (
        ///    [ID]        INT      DEFAULT ((0)) NOT NULL,
        ///	[FF]  TINYINT       DEFAULT ((0)) NULL,
        ///    [FS]  TINYINT       DEFAULT ((0)) NULL,
        ///	PRIMARY KEY (ID)
        ///);.
        /// </summary>
        internal static string Create_VoennaaTematika {
            get {
                return ResourceManager.GetString("Create_VoennaaTematika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Rules] (
        ///    [ID]        INT      IDENTITY(0,1),
        ///    [Priroda]       TINYINT       DEFAULT 0 NOT NULL,
        ///    [OtdihNaPrirode]    TINYINT       DEFAULT 0 NOT NULL,
        ///    [Dostoprimech]       TINYINT       DEFAULT 0 NOT NULL,
        ///    [TempSred]    TINYINT       DEFAULT 0 NOT NULL,
        ///    [Name]      VARCHAR (150) NULL
        ///	PRIMARY KEY (ID)
        ///);
        ///CREATE TABLE [dbo].[AktivniiOtdih] (
        ///    [ID]        INT      DEFAULT ((0)) NOT NULL,
        ///	[IDPersonal]        INT      IDENTITY(0,1),
        ///	[FF]  TINYINT        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Criate_Tables {
            get {
                return ResourceManager.GetString("Criate_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS dbo.Rules;
        ///DROP TABLE IF EXISTS dbo.AktivniiOtdih;
        ///DROP TABLE IF EXISTS dbo.Arhitectura;
        ///DROP TABLE IF EXISTS dbo.BolshieGoroda;
        ///DROP TABLE IF EXISTS dbo.Gori;
        ///DROP TABLE IF EXISTS dbo.MalenkieGoroda;
        ///DROP TABLE IF EXISTS dbo.OtdihVKompanii;
        ///DROP TABLE IF EXISTS dbo.Reki;
        ///DROP TABLE IF EXISTS dbo.SostoanieZdorovia;
        ///DROP TABLE IF EXISTS dbo.Temp_Hight;
        ///DROP TABLE IF EXISTS dbo.Temp_Low;
        ///DROP TABLE IF EXISTS dbo.VoennaaTematika;.
        /// </summary>
        internal static string DropsTablesString {
            get {
                return ResourceManager.GetString("DropsTablesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1000
        ///	R.ID, R.Name AS &apos;R:Resting-place&apos;,
        ///    AO.FF AS &apos;AO:Prefer active rest&apos;, AO.FS AS &apos;AO:Change of scenery&apos;, AO.FT AS &apos;AO:Extreme rest&apos;,
        ///	OvK.FF AS &apos;OvK:Big company&apos;, OvK.FS AS &apos;OvK:Small company&apos;,
        ///	R.Priroda AS &apos;R:Nature&apos;, R.OtdihNaPrirode AS &apos;R:Rest on nature&apos;,
        ///	A.FF AS &apos;A:Historical&apos;, A.FS AS &apos;A:Modern&apos;,
        ///	BG.FF AS &apos;BG:Industrials&apos;, BG.FS AS &apos;BG:Capitals&apos;, BG.FT AS &apos;BG:Regionals&apos;,
        ///	MG.FF AS &apos;MG:Provincials&apos;, MG.FS AS &apos;MG:Villages&apos;, 
        ///	R.Dostoprimech AS &apos;R:Attractions&apos;,
        ///	VT.FF AS &apos;VT: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectAllAlternative {
            get {
                return ResourceManager.GetString("SelectAllAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1000
        ///	R.ID, R.Name AS &apos;R:Resting-place&apos;,
        ///    AO.FF AS &apos;AO:Prefer active rest&apos;, AO.FS AS &apos;AO:Change of scenery&apos;, AO.FT AS &apos;AO:Extreme rest&apos;,
        ///	OvK.FF AS &apos;OvK:Big company&apos;, OvK.FS AS &apos;OvK:Small company&apos;,
        ///	R.Priroda AS &apos;R:Nature&apos;, R.OtdihNaPrirode AS &apos;R:Rest on nature&apos;,
        ///	A.FF AS &apos;A:Historical&apos;, A.FS AS &apos;A:Modern&apos;,
        ///	BG.FF AS &apos;BG:Industrials&apos;, BG.FS AS &apos;BG:Capitals&apos;, BG.FT AS &apos;BG:Regionals&apos;,
        ///	MG.FF AS &apos;MG:Provincials&apos;, MG.FS AS &apos;MG:Villages&apos;, 
        ///	R.Dostoprimech AS &apos;R:Attractions&apos;,
        ///	VT.FF AS &apos;VT: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectAllString {
            get {
                return ResourceManager.GetString("SelectAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	R.ID, R.Name
        ///FROM
        ///    [Rules] R
        ///.
        /// </summary>
        internal static string SelectNameAndID {
            get {
                return ResourceManager.GetString("SelectNameAndID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1000
        ///	R.ID, R.Name AS &apos;R:Resting-place&apos;,
        ///    AO.FF AS &apos;AO:Prefer active rest&apos;, AO.FS AS &apos;AO:Change of scenery&apos;, AO.FT AS &apos;AO:Extreme rest&apos;,
        ///	OvK.FF AS &apos;OvK:Big company&apos;, OvK.FS AS &apos;OvK:Small company&apos;,
        ///	R.Priroda AS &apos;R:Nature&apos;, R.OtdihNaPrirode AS &apos;R:Rest on nature&apos;,
        ///	A.FF AS &apos;A:Historical&apos;, A.FS AS &apos;A:Modern&apos;,
        ///	BG.FF AS &apos;BG:Industrials&apos;, BG.FS AS &apos;BG:Capitals&apos;, BG.FT AS &apos;BG:Regionals&apos;,
        ///	MG.FF AS &apos;MG:Provincials&apos;, MG.FS AS &apos;MG:Villages&apos;, 
        ///	R.Dostoprimech AS &apos;R:Attractions&apos;,
        ///	VT.FF AS &apos;VT: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectTOPaLL {
            get {
                return ResourceManager.GetString("SelectTOPaLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpertSystem.
        /// </summary>
        internal static string StartFormName {
            get {
                return ResourceManager.GetString("StartFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SUBNODE_ONE AktivniiOtdih;               -Активный Отдых
        ///             *                      byte FF;            ---Предпочитает активный отдых
        ///             *                      byte FS;            ---Любит смену обстановки
        ///             *                      byte FT;            ---Экстримальный отдых
        ///             * SUBNODE_ONE OtdihVKompanii;              -Отдых в компании
        ///             *                      byte FF;            ---Большая компания
        ///             *                      byte FS;       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructNODELogic {
            get {
                return ResourceManager.GetString("StructNODELogic", resourceCulture);
            }
        }
    }
}
